// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Frontend",
      items: [
        "frontend/version-control-and-web-foundations",
        "frontend/advanced-styling-and-layout",
        "frontend/javascript-core-part-1",
        "frontend/javascript-core-part-2",
        "frontend/async-javascript-and-apis",
        "frontend/browser-fundamentals-and-modern-tools",
        "frontend/typescript-and-build-tools",
        "frontend/react-fundamentals",
        "frontend/react-state-and-effects",
        "frontend/react-ecosystem-and-routing",
        "frontend/global-state-and-testing",
        "frontend/advanced-patterns-and-production",
      ],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
